services:
  nginx:
    container_name: hass-control
    image: nginx:alpine
    restart: always
    ports:
      - 8556:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/data/hass
